### ISSUE TITLE
AttributeError: 'Pupil' object has no attribute 'clip'

### ISSUE THREAD

**Issue by psychemedia** [brandondube/prysm#1]
Notebook https://github.com/brandondube/prysm/blob/master/Examples/Pupils.ipynb raises an error against the current pypi package:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-5187cd26f916> in <module>()
      3 xx, yy = np.meshgrid(x,y)
      4 p.phase = np.cos(xx*1.5) * np.sin(yy*1.5)
----> 5 p.clip();  # if you modify the phase, you should call .clip to re-enforce the mask
      6 
      7 # pupils can be plotted in 2D

AttributeError: 'Pupil' object has no attribute 'clip'
```

**Comment by psychemedia** [comment]
Hi @brandondube 

I'm on a trawl at the moment trying to find packages across a whole range of subject areas that can be used to support the creation of a wide variety of media assets for use in open educational materials - eg https://notebooks.azure.com/OUsefulInfo/libraries/gettingstarted/html/3.4.0%20Optics.ipynb
At the moment am just trying to find candidate packages / get quick examples working.

On my next pass of that notebook I hope to flesh it out a bit ore with some fuller and better annotated examples that show how to create various sorts of output asset that might be useful as worked examples, or part of assessment materials, in a higher and postgraduate educational context. When I do that, if I can figure out patches to `prysm` I'll do so and post them back here, or as a PR.

**Comment by psychemedia** [comment]
Thanks - my first pass was a "note to self" as much as anything that packages exist, and a demo just to check they work on Azure. Second / third pass will be to try to find some current teaching materials 
 with figures and diagrams and then try to recreate them using the tools I've found.

**Comment by brandondube** [comment]
Hi,

The docs have matured quite a bit these past months.  While they are still below the standard of, say, Scipy, they are usable I think.  I am going to close this issue as part of end-of-year cleanup.  Please reopen it if you disagree with this decision.
