### ISSUE TITLE
mft.x already a meshgrid, prysm.psf.encircled_energy(psf, dx, radius)  tries to meshgrid a meshgrid

### ISSUE THREAD

**Issue by courtney-barrer** [brandondube/prysm#113]
Hello, 
I'm enjoying using prysm.__version__ '0.21.1'. However noticed that prysm.psf.encircled_energy keeps crashing. When inspecting I've realised on line 314 we have nx, ny = np.meshgrid(mtf.x, mtf.y). However mtf.x , mtf.y is already a meshgrid. So the function is meshgriding a meshed grid. Setting  nx, ny = mtf.x, mtf.y seems to fix the issue. 
Thanks for the great work!

**Comment by brandondube** [comment]
Thanks for the bug report, I fixed this just now in e41a038!  Glad you're enjoying the library :)
