### ISSUE TITLE
Raytracing

### ISSUE THREAD

**Issue by brandondube** [brandondube/prysm#13]
It is conceivable that one day we might want prysm to have a raytracing engine.  Addition of such a feature will require considerable planning and discussion, followed by an extended period of hard work.

**Comment by JakobSilbermann** [comment]
Hello,
i did some research on it and found some other projects on github on raytracing. Would it not make sense to somehow incorporate them in prysm. I found https://github.com/mjhoptics/ray-optics [Michael Hayford] very good.

**Comment by brandondube** [comment]
Raytracing is a nice-to-have for prysm.  I can imagine, for example, modeling a system with misalignments via raytracing and then meshing the rays to make OPD and amplitude maps for the physical optics side.

Mike Hayford's module there is indeed very good.

Incorporating it or another into prysm is a bit tougher.  What you might want raytracing in prysm for has a very different sense of the ray grids desired and outputs desired (for example, a spot diagram is totally uninteresting for what I'd want raytracing for).

Several of them, Mike's included, have a POPPY-esque concept of "set up a run, then run it."  That style is quite incompatible to the modeling throughput prysm is designed for.  As an example, at work, a forward model of a system I work with daily is often executed millions of times per day.  I would not be surprised if I've passed a billion forward models over its lifetime.  That sort of exascale modeling and "tape machine" type architectures are hard to combine (the meta-machinery for the latter is too much "unproductive" overhead).

**Comment by JakobSilbermann** [comment]
Ok, i get the point thank you for your feedback.

**Comment by brandondube** [comment]
Spencer & Murty's algorithm was implemented in 566d6ed31c6b13b907bd846976d255d273107b3d and f591c30f85ff3f0a3fcf7e2aaacfb3fd92879291

I still need to add all of the other polynomial surface types, and implement even aspheres and XY polynomials.  But maybe for now I will not implement either since they are inferior to orthogonal polynomials.

A test suite is needed, and better graphing code (still sequestered in some dev notebooks).

Rotated surfaces may be implemented wrong(?).  Tilting an image plane results in an off-axis raytrace, which is counter to my expectation.

Closing this issue now in favor of new issues to go under #60 for specific extensions to what is implemented now
