### ISSUE TITLE
Codebase appears in violation of the BSD license

### ISSUE THREAD

**Issue by sobotka** [brandondube/prysm#2]
It would seem this code base utilizes code from Colour: https://github.com/colour-science/colour.

The MIT license as of last check, is not compatible with the BSD in the direction you are attempting I believe.

Further, you have failed to attribute the source code appropriately to meet the BSD requirements laid out in Colour.

**Comment by KelSolaar** [comment]
Hi @sobotka,

We have already privately notified the author and would be keen on avoiding public escalation and have a peaceful resolving of the issue.

Bests,

Thomas

**Comment by brandondube** [comment]
@sobotka I ask that you specifically point to code I have taken from colour that is not so simple (e.g. x = X / (X + Y + Z)) so as to not have alternative implementations.

**Comment by sobotka** [comment]
So you want me to actually crawl through your commits and show where you clearly ported code from colour? Seriously?

There is an easy resolution here, albeit in two parts:
 * License the code under a compatible license. BSD three clause or forward.
 * Document attribution accordingly.

Given the trivial nature of the two fixes above, one can only be led to believe that something ulterior is at work.

**Comment by brandondube** [comment]
You claim I stole code; show that I did.

**Comment by sobotka** [comment]
I am an adult here, and I certainly don't have to go through your code commits to show where you removed instances to Colour, maintained naming conventions that are unique to colour, point out the Yapf formatting your duplicated code contains, highlight your colorimetry.py commits, etc.

Or do I?

**Comment by KelSolaar** [comment]
Hi,

For reference, @brandondube closed #1 which we opened to solve gracefully the license infringement.

Cheers,

**Comment by lgritz** [comment]
@sobotka  BSD is not "viral" -- incorporating a small part of a BSD-licensed project doesn't require him to relicense his whole project under BSD. It's enough to document "this project is MIT, except for parts X and Y which are ported from project Z and distributed under the BSD license."

@brandondube The point that the code is not complex and could have been recoded is beside the point. It was taken from another project -- you explicitly acknowledged this when your commit comment was "port color coordinate transforms from colour."

Your obligations here are truly minimal -- all you need to do to be in compliance is to acknowledge in your license and docs where the code came from. You can see that the Colour project itself does this for code it incorporated from elsewhere: https://github.com/colour-science/colour/blob/develop/LICENSE (see the bottom, that's all they want you to do). That's what all responsible projects do.

I know you're just a student and mean no harm here, but word of this is spreading rapidly in professional color and graphics circles. I think you will be ill-served in the long run by leaving a continuing digital trail of unprofessional conduct, when instead you could just comply with the license obligations with a two line addendum to your project docs.
