### ISSUE TITLE
Wrong calculation of self.center_y, self.center_x for Convolvable class

### ISSUE THREAD

**Issue by ira7bar** [brandondube/prysm#2]
[Current](https://github.com/brandondube/prysm/blob/dev/prysm/convolution.py#L50) calculation of center_x and center_y of Convolvable class is:
`self.center_y, self.center_x = int(m.ceil(self.samples_y / 2)), int(m.ceil(self.samples_x / 2))`
This gives the wrong values for odd dimensions (e.g. 10 -> 6 instead of 5) as these values are used as indices later, for example in plot_slice_xy().
In other classes (e.g. [MTF](https://github.com/brandondube/prysm/blob/master/prysm/otf.py#L60)), this is calculated as:
`self.center_x = self.samples_x // 2`
`self.center_y = self.samples_y // 2`
Which gives the expected results.

I'm using prysm version 0.14.0 with python 3.6.7 (installed via pip).

Thank you.

**Comment by brandondube** [comment]
Thanks for the catch.  I haven't touched the MTF of PSF (Convolvable) classes in quite a long time --  I think more than a year.  The Convolvable one is correct in base 1 indexes, which is probably why I did that :)

Anyway.  Resolved in 574ac5395c3c2cdc334f7a95849278bf85172a9a.  If you need this today you can install from git, which will put you on 0.15 dev.  The other changes in the release thus far are all to do with interferograms, and 0.15 is due in probably mid-march.
