### ISSUE TITLE
Return of the Object-Oriented API

### ISSUE THREAD

**Issue by brandondube** [brandondube/prysm#47]
The changes from prysm v0.19 to v0.20 basically deleted most of the object oriented-ness of the library.  This has made it easier to write prysm, but the API is pretty radically different to its contemporaries (PROPER/POPPY/HCIpy/FALCO).  This can be intimidating for some users, who may not be familiar with or want to learn this.

We should consider building out an object oriented API more similar to other projects.  The core propagation and interferometry modules are already really object-oriented.  Maybe this is a concept of `OpticalSystem` (from POPPY) that is missing.

**Comment by egemenimre** [comment]
This seems like an old issue, but I would wholeheartedly support an OO high level `OpticalSystem` object - I have one already for my own pet project [opticks](https://github.com/egemenimre/opticks) where an optical system has an aperture (circle with obscuration etc), a list of Wavefront objects (for each wavelength for now) and can compute the psf, for example.

**Comment by brandondube** [comment]
This has stalled out for a long time, basically because it is difficult to design a performant object oriented API that doesn't have huge amounts of meta code to handle various forms of input.  prysm was able to gain _many_ features while [shrinking ~33% in size](https://github.com/brandondube/prysm/blob/master/sloccounts.csv) over several versions, by deleting a few dozen classes and going to a mostly array oriented, procedural style.  That is sort of evident in your `opticks` package itself, where there is ~300 lines of wrapper around prysm in `optics.py` that doesn't actually _do_ anything, it is just interface code (or docstrings).

For example, in your wrapper the user provides a set of wavefronts.  But they presumably have the same `dx` and so on, so there is a bit of a more optimal representation.  And in `zernike_opd`, the expensive creation of the basis functions happens anytime someone wants to make a new phase screen.

I have not been actively working on this at all in the time since making this tracking issue (or set of issues), but there is no clear design (to me) that keeps the high performance and relative simplicity of prysm, while having a more OO coding style

I have generally found that for each unique type of problem I encounter (simple pupil to PSF, or coronagraph, or interferometer, etc) a fairly nature OO API appears, but they are all unique to each other.

**Comment by egemenimre** [comment]
Thanks for the detailed response (and taking the pains to look at my code). I understand that `prysm` aims to be scalable and fast, whereas `opticks` aims to be easy to set up and accessible for a large audience - or at least for the systems engineering tasks. Therefore I don't mind wrapping prysm for my purposes, consciously trading performance as I do it. OO by design *limits* flexibility, and then you either have to write a lot of code to put back that flexibility back in place or, in my case, resort to the original prysm.

**Comment by brandondube** [comment]
I hope "resort to" is not meant with pain :)  I think the design goal is prysm is perhaps best stated as "the tool is made so that it stays out of the way of an expert user," but it does give merit to a general sense of intelligibility and/or usability by anyone

**Comment by egemenimre** [comment]
As a newcomer to the field of optics, I'm still trying to wrap my head around the physical modelling under the hood as well as the code, so `prysm` is still not so easy for me to grasp - but I'll get there. :)
