### ISSUE TITLE
revised thinfilm code is incompatible with infinite thicknesses

### ISSUE THREAD

**Issue by brandondube** [brandondube/prysm#82]
In v0.20, the thin-film code is perfectly happy with infinitely thick layers, as for a substrate.  However, in v0.21, the code breaks and produces incorrect outputs when thicknesses of infinity are present.  This regression should be corrected.

**Comment by derek33125** [comment]
Still reproducible on the latest PyPI release (`prysm==0.21.1`):

```python
import numpy as np
from prysm.thinfilm import multilayer_stack_rt

r_inf, _ = multilayer_stack_rt([(1.0, 0.0), (1.5, np.inf)], 0.55, "s", aoi=0)
r_big, _ = multilayer_stack_rt([(1.0, 0.0), (1.5, 1e12)], 0.55, "s", aoi=0)
print(r_inf)  # nan+nanj
print(r_big)  # ~ -0.2+…j  (matches Fresnel air→glass at normal incidence)
```

So infinite thickness still yields non-finite `r`, while a large finite thickness is fine.
