### ISSUE TITLE
docstring error in prysm.propagation.focus/unfocus_fixed_sampling

### ISSUE THREAD

**Issue by Jashcraf** [brandondube/prysm#94]
<img width="784" alt="image" src="https://github.com/brandondube/prysm/assets/25557892/e32b42c0-3aa5-4a4a-a39b-8657ea3a3905">

I think the `input_dx` and `output_dx` are flipped in the docstrings, standby for PR

**Comment by brandondube** [comment]
This is fixed now on master, closing https://github.com/brandondube/prysm/blob/master/prysm/propagation.py#L166
